import pytest

from app.settings import LibraryConfig, PathMapping, Settings
from app.worker import search_index
from app.worker.media_client import MovieResult
from app.worker.style_preview import (
    extract_background_frame,
    pick_random_movie_frame_source,
    render_style_preview,
)
from app.worker.subprocess_utils import run_and_capture
from app.worker.subtitle_render import STYLE_PRESETS


@pytest.mark.anyio
async def test_render_style_preview_produces_a_png(tmp_path):
    png_bytes = await render_style_preview(
        STYLE_PRESETS["classic"],
        fonts_dir=tmp_path / "fonts",
        scratch_dir=tmp_path / "scratch",
    )
    assert png_bytes[:8] == b"\x89PNG\r\n\x1a\n"  # PNG magic number


@pytest.mark.anyio
async def test_render_style_preview_accepts_a_real_background_frame(tmp_path):
    background_path = tmp_path / "background.png"
    await run_and_capture(
        [
            "ffmpeg", "-y", "-f", "lavfi", "-i", "color=size=480x270:color=red",
            "-frames:v", "1", "-vcodec", "png", str(background_path),
        ],
        timeout_seconds=10.0, error_prefix="test background generation", capture_stdout=False,
    )
    png_bytes = await render_style_preview(
        STYLE_PRESETS["classic"],
        fonts_dir=tmp_path / "fonts",
        scratch_dir=tmp_path / "scratch",
        background_path=background_path,
    )
    assert png_bytes[:8] == b"\x89PNG\r\n\x1a\n"


@pytest.mark.anyio
async def test_extract_background_frame_produces_a_correctly_sized_png(tmp_path):
    # A short real (synthetic, generated by ffmpeg itself) video — real
    # ffmpeg command construction (fast seek, scale+crop) exercised
    # end-to-end rather than mocked, per this project's standing rule to
    # verify worker-layer ffmpeg changes against the real binary.
    source_path = tmp_path / "source.mp4"
    await run_and_capture(
        [
            "ffmpeg", "-y", "-f", "lavfi", "-i", "testsrc=size=1280x720:rate=1:duration=5",
            "-pix_fmt", "yuv420p", str(source_path),
        ],
        timeout_seconds=20.0, error_prefix="test source generation", capture_stdout=False,
    )
    scratch_dir = tmp_path / "scratch"
    output_path = await extract_background_frame(str(source_path), scratch_dir)
    assert output_path.exists()
    assert output_path.parent == scratch_dir
    png_bytes = output_path.read_bytes()
    assert png_bytes[:8] == b"\x89PNG\r\n\x1a\n"


class _FakeMedia:
    def __init__(self, movie_library_names, movies_by_id):
        self.movie_library_names = movie_library_names
        self.show_library_names = frozenset()
        self._movies_by_id = movies_by_id

    def get_movie(self, media_id):
        return self._movies_by_id[media_id]


def _movie(media_id, library_name, source_path):
    return MovieResult(
        media_id=media_id, title=f"Movie {media_id}", year=2020, duration_ms=6_000_000,
        thumb_url=None, source_path=source_path, guid=f"guid-{media_id}", library_name=library_name,
    )


def _cache_title(db_path, guid, media_id, title, library_name):
    search_index.upsert_title(
        db_path, guid=guid, media_id=media_id, title=title, library_name=library_name,
        source="sidecar", sidecar_path=None, stream_index=None, entries=[], fingerprint=None,
    )


def _settings_with_mapping(tmp_path, library_name, path_prefix, container_root):
    return Settings(
        discord_token="x", plex_url="http://x", plex_token="x",
        cache_dir=tmp_path / "cache",
        libraries=[LibraryConfig(
            name=library_name,
            path_mappings=[PathMapping(path_prefix=path_prefix, container_path=str(container_root))],
        )],
    )


@pytest.mark.anyio
async def test_pick_random_movie_frame_source_returns_none_with_no_cached_movies(tmp_path):
    media = _FakeMedia(movie_library_names=frozenset({"Movies"}), movies_by_id={})
    settings = Settings(discord_token="x", plex_url="http://x", plex_token="x", cache_dir=tmp_path / "cache")
    result = await pick_random_movie_frame_source(media, settings, settings.quote_index_db_path)
    assert result is None


@pytest.mark.anyio
async def test_pick_random_movie_frame_source_ignores_non_movie_libraries(tmp_path):
    db_path = tmp_path / "cache" / "quote_index.db"
    _cache_title(db_path, "guid-1", "1", "A Show", "TV Shows")

    media = _FakeMedia(movie_library_names=frozenset({"Movies"}), movies_by_id={})
    settings = Settings(discord_token="x", plex_url="http://x", plex_token="x", cache_dir=tmp_path / "cache")
    result = await pick_random_movie_frame_source(media, settings, db_path)
    assert result is None


@pytest.mark.anyio
async def test_pick_random_movie_frame_source_resolves_a_real_file(tmp_path):
    real_dir = tmp_path / "real_media"
    real_dir.mkdir()
    real_file = real_dir / "movie.mp4"
    real_file.write_bytes(b"fake video bytes")

    db_path = tmp_path / "cache" / "quote_index.db"
    _cache_title(db_path, "guid-1", "1", "A Movie", "Movies")

    media = _FakeMedia(
        movie_library_names=frozenset({"Movies"}),
        movies_by_id={"1": _movie("1", "Movies", "/media/movies/movie.mp4")},
    )
    settings = _settings_with_mapping(tmp_path, "Movies", "/media/movies", real_dir)

    result = await pick_random_movie_frame_source(media, settings, db_path)
    assert result is not None
    movie, container_path = result
    assert movie.media_id == "1"
    assert container_path == str(real_file)


@pytest.mark.anyio
async def test_pick_random_movie_frame_source_skips_a_title_whose_file_is_gone(tmp_path):
    db_path = tmp_path / "cache" / "quote_index.db"
    _cache_title(db_path, "guid-1", "1", "A Movie", "Movies")

    media = _FakeMedia(
        movie_library_names=frozenset({"Movies"}),
        movies_by_id={"1": _movie("1", "Movies", "/media/movies/missing.mp4")},
    )
    # No path mapping at all configured for "Movies" — path_mappings_for
    # raises SettingsError, which must be treated as "this one didn't
    # resolve" rather than propagating and failing the whole pick.
    settings = Settings(discord_token="x", plex_url="http://x", plex_token="x", cache_dir=tmp_path / "cache")

    result = await pick_random_movie_frame_source(media, settings, db_path)
    assert result is None
